project_id = "svdswlryhqmdzmilslyz"

[functions.track-engagement]
verify_jwt = false

[functions.get-analytics]
verify_jwt = true

[functions.admin-download-products]
verify_jwt = true

[functions.admin-download-brand-insights]
verify_jwt = true

[functions.admin-bulk-upload]
verify_jwt = true
